Repository openshift/training, pull requests merged in 2019-03, with the labels that each got.

#438 docs: Drop openshiftClusterID
  docs/05-infrastructure-nodes.md
  docs/06-cleanup.md
Labels: size/S

#443 fixed Machine Sets reference
  docs/04-scaling-cluster.md
Labels: needs-ok-to-test, size/XS

#441 Pair quote
  docs/05-infrastructure-nodes.md
Labels: size/XS

#447 fix installer version
  docs/05-infrastructure-nodes.md
Labels: size/XS

#439 Tweaks after beta drop
  docs/01-prerequisites.md
  docs/03-explore.md
  docs/04-scaling-cluster.md
  img/all-systems.png
  img/grafana.png
  img/machine-set.png
  img/scale-nodes.png
Labels: needs-ok-to-test, size/XL

#433 Added a tips and tricks section
  README.md
  docs/08-tips-and-tricks.md
Labels: size/L

#432 Added scaling workers with oc scale
  docs/02-install.md
  docs/03-explore.md
  docs/04-scaling-cluster.md
Labels: size/S

#448 added MachineHealthCheck example
  docs/05-infrastructure-nodes.md
Labels: needs-ok-to-test, size/M

#450 beta3 instructions with links out to docs.openshift site
  README.md
  assets/create-autoscalers.sh
  assets/logging-cr.yaml
  assets/logging-project.yaml
  docs/01-prerequisites.md
  docs/02-install.md
  docs/03-explore.md
  docs/04-scaling-cluster.md
  docs/05-infrastructure-nodes.md
  docs/06-authentication.md
  docs/07-extensions.md
  docs/08-logging.md
  docs/09-istio.md
Labels: size/XXL
