Repository openshift/training, pull requests merged in 2019-01, with the labels that each got.

#382 first crack at the beta instructions
  README.md
  docs/01-prerequisites.md
  docs/02-install.md
Labels: size/L

#383 [WIP] Beta changes
  04-scaling-cluster.md
  docs/01-prerequisites.md
  docs/02-install.md
  docs/03-explore.md
  docs/04-cleanup.md
  docs/05-cleanup.md
Labels: size/L

#393 Fix typos
  docs/01-prerequisites.md
  docs/04-scaling-cluster.md
Labels: size/XS

#397 Various fixes and updates
  docs/01-prerequisites.md
  docs/02-install.md
  docs/04-scaling-cluster.md
  docs/05-cleanup.md
Labels: size/M

#395 Fixes #389
  docs/02-install.md
  docs/05-cleanup.md
Labels: size/M

#396 Fix several typos
  docs/01-prerequisites.md
  docs/compute/03-highly-available-control-plane.md
  docs/compute/05-highly-available-workers.md
  docs/nodes/02-redhat-coreos.md
  docs/operators/01-understanding-operators.md
  docs/operators/02-cluster-version-operator.md
Labels: size/S

#398 changes for --dir option
  docs/02-install.md
Labels: size/S

#405 fixes #403
  docs/02-install.md
Labels: size/XS

#406 adds a note for using the AWS cli to find hostnames
  docs/03-explore.md
Labels: size/XS

#407 Beta changes
  assets/cluster-autoscaler.yaml
  assets/machine-autoscale-example.yaml
  assets/machine-autoscale-us-east-2a.yaml
  assets/machine-autoscale-us-east-2b.yaml
  assets/machine-autoscale-us-east-2c.yaml
  docs/02-install.md
  docs/04-scaling-cluster.md
Labels: size/L

#417 docs/operators/03-second-level-operators: 'console' highlighting
  docs/operators/03-second-level-operators.md
Labels: size/S

#414 docs/01-prerequisites: No pre-formatting for "Configure everything ..."
  docs/01-prerequisites.md
Labels: size/XS

#413 docs/01-prerequisites: Drop trailing whitespace for AWS Access Key ID
  docs/01-prerequisites.md
Labels: size/XS

#412 nodes/02-redhat-coreos: Remove space before crictl
  docs/nodes/02-redhat-coreos.md
Labels: size/XS

#411 docs/05-cleanup: Talk about metadata.json
  docs/05-cleanup.md
Labels: size/S

#409 Small suggestions
  docs/04-scaling-cluster.md
Labels: size/S

#415 docs/01-prerequisites: Use ~/.ssh/*.pub for pubkeys
  docs/01-prerequisites.md
Labels: size/S

#425 Fix broken link to configuration page
  docs/operators/04-operator-lifecycle-manager.md
Labels: needs-ok-to-test, size/XS
