Repository openshift/training, pull requests merged in 2019-02, with the labels that each got.

#426 Infra nodes
  docs/02-install.md
  docs/05-infrastructure-nodes.md
Labels: size/XL

#429 docs/03-explore: Remove untested documentation
  docs/03-explore.md
  docs/cli/01-accessing.md
  docs/compute/01-managing-compute.md
  docs/compute/02-control-plane.md
  docs/compute/03-highly-available-control-plane.md
  docs/compute/04-workers.md
  docs/compute/05-highly-available-workers.md
  docs/compute/06-cluster-autoscaler.md
  docs/compute/07-autoscaling-workers.md
  docs/compute/08-health-checks.md
  docs/compute/09-multiple-machine-pools.md
  docs/console/01-accessing.md
  docs/developer-experience/01-developer-experience.md
  docs/monitoring/01-understanding-monitoring.md
  docs/nodes/01-managing-nodes.md
  docs/nodes/02-redhat-coreos.md
  docs/nodes/03-machine-config.md
  docs/operators/01-understanding-operators.md
  docs/operators/02-cluster-version-operator.md
  docs/operators/03-second-level-operators.md
  docs/operators/04-operator-lifecycle-manager.md
  docs/operators/05-configuration.md
Labels: size/XXL

#428 Minor grammar fix
  docs/03-explore.md
Labels: size/XS

#431 Changed name to RHEL CoreOS
  docs/03-explore.md
Labels: size/S
